# Setup
title:        Not First But Best
tagline:      최혜선의 블로그
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       hyesun03(최혜선)
  url:        https://hyesun03.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
